#
# Eventing Kafka Dependency Specification
#

required = [
  "k8s.io/apimachinery/pkg/util/sets/types",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "knative.dev/pkg/codegen/cmd/injection-gen",
  "knative.dev/test-infra/scripts"
]

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[prune.project]]
  name = "k8s.io/code-generator"
  unused-packages = false
  non-go = false

[[prune.project]]
  name = "knative.dev/test-infra"
  non-go = false

[[prune.project]]
  name = "knative.dev/pkg"
  unused-packages = false
  non-go = false

# Align With Knative Eventing-Contrib
[[constraint]]
  name = "knative.dev/eventing-contrib"
  branch = "release-0.14"

# Align With Knative Eventing-Contrib
[[constraint]]
  name = "knative.dev/eventing"
  branch = "release-0.14"

# Align With Knative Eventing-Contrib
[[constraint]]
  name = "github.com/cloudevents/sdk-go"
  version = "v2.0.0-RC1"

[[constraint]]
  name = "github.com/confluentinc/confluent-kafka-go"
  version = "~v1.0.0"

# Using Old Azure Because We're Not On Go Modules : (
[[constraint]]
  name = "github.com/Azure/azure-event-hubs-go"
  version = "v1.3.1"

# Align With Knative Eventing-Contrib
[[override]]
  name = "gopkg.in/yaml.v2"
  version = "v2.2.4"

# For dependency below: Refer to issue https://github.com/golang/dep/issues/1799
[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"
  version="v1.4.7"
