# Default values for kafka.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# While the KafkaChannels and Knative Subscriptions can live in any user namespace, all
# management and runtime plane components will live in the knative-eventing namespace.
global:
  namespace:
    eventing: knative-eventing

# Image Information
image:
  repository: eu.gcr.io/kyma-project/incubator
  project: kafka-channel-controller
  tag: latest
  pullPolicy: Always

# Networking Configuration for the Pods container and the K8S Service
kafka:
  networking:
    container:
      metricsPort: 8081 # Port exposed by container for metrics
    service:
      metricsPort: 8081 # Port exposed by service for metrics

environment:
  # Valid values: local, confluent, azure
  kafkaProvider: local
  # Eventing-kafka Channel "Producer" Docker Image Path
  channelImage: eu.gcr.io/kyma-project/incubator/eventing-kafka-channel:latest
  channelReplicas: 1
  # Eventing-kafka Dispatcher "Consumer" Docker Image Path
  dispatcherImage: eu.gcr.io/kyma-project/incubator/eventing-kafka-dispatcher:latest
  dispatcherReplicas: 1
  defaultNumPartitions: 4
  defaultReplicationFactor: 1
  defaultKafkaConsumers: 4

channel:
  memoryRequest: 50Mi
  memoryLimit: 100Mi
  cpuRequest: 100m
  cpuLimit: 200m

dispatcher:
  memoryRequest: 50Mi
  memoryLimit: 128Mi
  cpuRequest: 300m
  cpuLimit: 500m

controller:
  memoryRequest: 25Mi
  memoryLimit: 50Mi
  cpuRequest: 20m
  cpuLimit: 100m
